import { defineFamily } from "../types";
export const dupontStyleConnectors = [
  ...defineFamily({
    manufacturer: "Generic",
    family: "DuPont-style 2.54 mm Single Row",
    series: "DUPONT-SR",
    pins: Array.from({ length: 12 }, (_, i) => i + 1),
    part: (n) => `DUPONT-SR-${n}`,
    pitchMm: 2.54,
    rows: 1,
    allowedAwg: [22, 28],
    renderer: "dupont",
    sourceDocument: "Generic 2.54 mm crimp housing convention",
    sourceStatus: "generic",
    latch: "friction",
    polarized: false,
    metadata: {
      warning:
        "DuPont-style is an ecosystem description, not one controlled part specification.",
    },
  }),
  ...defineFamily({
    manufacturer: "Generic",
    family: "DuPont-style 2.54 mm Dual Row",
    series: "DUPONT-DR",
    pins: [4, 6, 8, 10, 12, 16, 20, 24, 30, 40],
    part: (n) => `DUPONT-DR-${n}`,
    pitchMm: 2.54,
    rows: 2,
    allowedAwg: [22, 28],
    renderer: "dupont",
    sourceDocument: "Generic 2.54 mm crimp housing convention",
    sourceStatus: "generic",
    latch: "friction",
    polarized: false,
  }),
  ...defineFamily({
    manufacturer: "Amphenol",
    family: "Amphenol Mini-PV 2.54 mm",
    series: "PV",
    pins: [1, 2, 3, 4, 5, 6, 8, 10],
    part: (n) => `PV-HOUSING-${n}`,
    pitchMm: 2.54,
    rows: 1,
    allowedAwg: [22, 26],
    renderer: "dupont",
    datasheetUrl:
      "https://cdn.amphenol-cs.com/media/wysiwyg/files/documentation/datasheet/boardwiretoboard/bwb_pv_wtb.pdf",
    sourceDocument: "Amphenol PV wire-to-board and wire-to-wire system",
    sourceStatus: "manufacturer-verified",
    latch: "friction",
    polarized: false,
  }),
];
