import { defineFamily } from "../types";
import type { ConnectorDefinition } from "../types";

const ringTerminals: ConnectorDefinition[] = [10, 12, 14, 16, 18, 20, 22].map(
  (gauge) => ({
    id: `generic-crimp-ring-terminal-awg-${gauge}`,
    manufacturer: "Generic",
    family: "Generic Crimp-on Ring Terminal",
    name: `Generic Crimp-on Ring Terminal · ${gauge} AWG`,
    series: "GEN-RING",
    housingPartNumber: `RING-AWG-${gauge}`,
    pitchMm: null,
    pinCount: 1,
    rows: 1,
    allowedAwg: [gauge, gauge],
    renderer: "ring-terminal",
    sourceDocument: "Generic insulated crimp ring terminal",
    sourceStatus: "generic",
    latch: "none",
    polarized: false,
    metadata: { gauge: String(gauge), termination: "ring lug" },
  }),
);
export const genericConnectors = [
  ...ringTerminals,
  ...defineFamily({
    manufacturer: "Generic",
    family: "Generic Single Row",
    series: "GEN-SR",
    pins: Array.from({ length: 12 }, (_, i) => i + 1),
    part: (n) => `GEN-SR-${n}`,
    pitchMm: 2.54,
    rows: 1,
    allowedAwg: [18, 30],
    renderer: "single",
    sourceStatus: "generic",
    latch: "none",
    polarized: false,
  }),
  ...defineFamily({
    manufacturer: "Generic",
    family: "Generic Dual Row",
    series: "GEN-DR",
    pins: [4, 6, 8, 10, 12, 16, 20],
    part: (n) => `GEN-DR-${n}`,
    pitchMm: 2.54,
    rows: 2,
    allowedAwg: [18, 30],
    renderer: "dual",
    sourceStatus: "generic",
    latch: "none",
    polarized: false,
  }),
  ...defineFamily({
    manufacturer: "Generic",
    family: "Screw Terminal",
    series: "GEN-ST",
    pins: [2, 3, 4, 5, 6, 7, 8],
    part: (n) => `GEN-ST-${n}`,
    pitchMm: 5.08,
    rows: 1,
    allowedAwg: [12, 28],
    renderer: "terminal",
    sourceStatus: "generic",
    latch: "none",
    polarized: true,
  }),
];
