import { defineFamily } from "../types";
export const jstConnectors = [
  ...defineFamily({
    manufacturer: "JST",
    family: "JST XH",
    series: "XH",
    pins: [2, 3, 4, 5, 6],
    part: (n) => `XHP-${n}`,
    pitchMm: 2.5,
    rows: 1,
    allowedAwg: [22, 30],
    renderer: "jst-xh",
    datasheetUrl: "https://www.jst-mfg.com/product/index.php?lang=2&series=277",
    sourceDocument: "JST XH product profile / housing drawing",
    sourceStatus: "manufacturer-verified",
    latch: "friction",
    polarized: true,
  }),
  ...defineFamily({
    manufacturer: "JST",
    family: "JST PH",
    series: "PH",
    pins: [2, 3, 4, 5, 6],
    part: (n) => `PHR-${n}`,
    pitchMm: 2,
    rows: 1,
    allowedAwg: [24, 32],
    renderer: "jst-ph",
    datasheetUrl: "https://www.jst-mfg.com/product/pdf/eng/ePH.pdf",
    sourceDocument: "JST PH catalog ePH",
    sourceStatus: "manufacturer-verified",
    latch: "friction",
    polarized: true,
  }),
];
